gitlab-mysql:
  restart: always
  image: mysql:8.0.3
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=gitlabhq_production
    - MYSQL_USER=gitlab
    - MYSQL_PASSWORD=gitlab
  volumes:
    - ./docker/gitlab/mysql:/var/lib/mysql
    - ./docker/gitlab/logs/mysql:/var/log/mysql
gitlab:
  restart: always
  image: sameersbn/gitlab:10.2.5
  links:
    - gitlab-redis:redisio
    - gitlab-mysql:mysql
  environment:
    - DEBUG=false
    - TZ=Asia/Tokyo
    - GITLAB_TIMEZONE=Tokyo

    - GITLAB_SECRETS_OTP_KEY_BASE=tKg7dMMwbMctLnNbdCjqVRtXWn7RPNRvhrVFWVz7FhmzjjsJgW4JLnPhs7zMgkPJ
    - GITLAB_SECRETS_DB_KEY_BASE=XXWJWbrxXCCjbvdRK9XTnmqHsvNhpwbqcnXbCVzrvRzKPRkv9W4CFWnpvrrMcdR4
    - GITLAB_SECRETS_SECRET_KEY_BASE=KNJ7PfVLkjhmPWwvMHJKTXdtwpfRkKWTdTjvdxvH39Tk3JKWrVfgLL3Tx7XwMVjT

    - GITLAB_HOST=
    - GITLAB_PORT=
    - GITLAB_SSH_PORT=
    - GITLAB_RELATIVE_URL_ROOT=/gitlab

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=notifications@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=true
    - SMTP_DOMAIN=mailsv.itec.hankyu-hanshin.co.jp
    - SMTP_HOST=mailsv.itec.hankyu-hanshin.co.jp
    - SMTP_PORT=587
    - SMTP_USER=om7004
    - SMTP_PASS=w29zb*jg
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false
  volumes:
    - ./docker/gitlab/gitlab:/home/git/data
gitlab-redis:
  restart: always
  image: redis:3.2.11
  expose:
    - "6379"
  volumes:
    - ./docker/gitlab/redis:/var/lib/redis
redmine-mysql:
  restart: always
  image: mysql:8.0.3
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=redmine_production
    - MYSQL_USER=redmine
    - MYSQL_PASSWORD=redmine
  volumes:
    - ./docker/redmine/mysql:/var/lib/mysql
    - ./docker/redmine/logs/mysql:/var/log/mysql
redmine:
  restart: always
  image: sameersbn/redmine:3.4.2
  links:
    - redmine-mysql:mysql
  environment:
    - TZ=Asia/Tokyo

    - REDMINE_PORT=
    - REDMINE_HTTPS=false
    - REDMINE_RELATIVE_URL_ROOT=/redmine
    - REDMINE_SECRET_TOKEN=

    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15

    - REDMINE_CONCURRENT_UPLOADS=2

    - REDMINE_BACKUP_SCHEDULE=daily
    - REDMINE_BACKUP_EXPIRY=
    - REDMINE_BACKUP_TIME=

    - SMTP_ENABLED=true
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=mailsv.itec.hankyu-hanshin.co.jp
    - SMTP_HOST=mailsv.itec.hankyu-hanshin.co.jp
    - SMTP_PORT=587
    - SMTP_USER=om7004
    - SMTP_PASS=w29zb*jg
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_INTERVAL=30
  volumes:
    - ./docker/redmine/redmine:/home/redmine/data
    - ./docker/redmine/logs/redmine:/home/redmine/redmine/log
jenkins:
  restart: always
  image: jenkins:2.60.3
  environment:
    - JENKINS_OPTS=--prefix=/jenkins
  volumes:
    - ./docker/jenkins/jenkins:/var/jenkins_home
proxy:
  build: proxy
  links:
    - gitlab:gitlab
    - redmine:redmine
    - jenkins:jenkins
  ports:
    - "80:80"
